name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create virtual environment
        run: python -m venv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install uv
          uv venv  # создаем окружение для uv
          uv pip install -e .
          pip install flake8 pytest  # явно ставим нужные пакеты

      - name: Run linter and pytest
        run: |
          source venv/bin/activate
          make check
